### ISSUE TITLE
Проблема с запуском генерации монет

### ISSUE THREAD

**Issue by GoldArmyYT** [deluvsushi/AminoCoinGeneratorBo#18]
Как бы я не вводил community ссылку, скрипт выдаёт это

Traceback (most recent call last):
  File "AminoCoinGeneratorBo.py", line 7, in <module>
    main_functions.main()
  File "/home/ivan/AminoCoinGeneratorBo/coin_generator_configs/main_functions.py", line 100, in main
    main_process()
  File "/home/ivan/AminoCoinGeneratorBo/coin_generator_configs/main_functions.py", line 80, in main_process
    ndc_id = link_Info["linkInfoV2"]["extensions"]["community"]["ndcId"]
KeyError: 'linkInfoV2

**Comment by xAkilax** [comment]
i also have the same problem
