### ISSUE TITLE
ModuleNotFoundError: No module named 'json_minify'

### ISSUE THREAD

**Issue by Ahmed337414** [deluvsushi/AminoCoinGeneratorBo#19]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AminoCoinGeneratorBo/AminoCoinGeneratorBo.py", line 3, in <module>
    from coin_generator_configs import main_functions
  File "/data/data/com.termux/files/home/AminoCoinGeneratorBo/coin_generator_configs/main_functions.py", line 6, in <module>
    from .library import aminoboi
  File "/data/data/com.termux/files/home/AminoCoinGeneratorBo/coin_generator_configs/library/aminoboi.py", line 13, in <module>
    from json_minify import json_minify
ModuleNotFoundError: No module named 'json_minify'

sir please help ....please

**Comment by deluvsushi** [comment]
pip install json_minify

**Comment by Ahmed337414** [comment]
Sir i install json_minify using pip the another error .
