### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'accounts.json'

### ISSUE THREAD

**Issue by Ahmed337414** [deluvsushi/AminoCoinGeneratorBo#20]
version : 2.9
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AminoCoinGeneratorBo/AminoCoinGeneratorBo.py", line 3, in <module>
    from coin_generator_configs import main_functions
  File "/data/data/com.termux/files/home/AminoCoinGeneratorBo/coin_generator_configs/main_functions.py", line 11, in <module>
    with open("accounts.json") as data:
FileNotFoundError: [Errno 2] No such file or directory: 'accounts.json'

Sir, what is next...please can update the code

**Comment by deluvsushi** [comment]
read the instruction
