### ISSUE TITLE
jsondecodeerror : extra data: line 8 column 2 (char183)

### ISSUE THREAD

**Issue by Ahmed337414** [deluvsushi/AminoCoinGeneratorBo#27]
I past accounts.json in the script but still not it's showing an error I don't understand please help me.

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  main.dict)
  File "<string>", line 1, in <module>
  File "/storage/emulated/0/Download/Telegram/AminoCoinGeneratorBo-main/AminoCoinGeneratorBo-main/src/utils.py", line 12, in <module>
    data = load(database)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/json/init.py", line 293, in load
    return loads(fp.read(),
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/json/init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 8 column 2 (char 183) 

[Program finished]

**Comment by deluvsushi** [comment]
fix your account.json file
